-- MySQL Script generated by MySQL Workbench
-- Fri Nov  7 09:35:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema globalgadgets_dw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema globalgadgets_dw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `globalgadgets_dw` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `globalgadgets_dw` ;

-- -----------------------------------------------------
-- Table `globalgadgets_dw`.`dim_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globalgadgets_dw`.`dim_country` (
  `country_id` INT NOT NULL,
  `country_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globalgadgets_dw`.`dim_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globalgadgets_dw`.`dim_state` (
  `state_id` INT NOT NULL,
  `state_name` VARCHAR(50) NULL DEFAULT NULL,
  `country_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`state_id`),
  INDEX `country_id` (`country_id` ASC) VISIBLE,
  CONSTRAINT `dim_state_ibfk_1`
    FOREIGN KEY (`country_id`)
    REFERENCES `globalgadgets_dw`.`dim_country` (`country_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globalgadgets_dw`.`dim_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globalgadgets_dw`.`dim_city` (
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(50) NULL DEFAULT NULL,
  `state_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `state_id` (`state_id` ASC) VISIBLE,
  CONSTRAINT `dim_city_ibfk_1`
    FOREIGN KEY (`state_id`)
    REFERENCES `globalgadgets_dw`.`dim_state` (`state_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globalgadgets_dw`.`dim_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globalgadgets_dw`.`dim_customer` (
  `customer_id` INT NOT NULL,
  `customer_name` VARCHAR(100) NULL DEFAULT NULL,
  `gender` VARCHAR(10) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globalgadgets_dw`.`dim_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globalgadgets_dw`.`dim_location` (
  `location_id` INT NOT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globalgadgets_dw`.`dim_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globalgadgets_dw`.`dim_product` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(100) NULL DEFAULT NULL,
  `category` VARCHAR(50) NULL DEFAULT NULL,
  `brand` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globalgadgets_dw`.`dim_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globalgadgets_dw`.`dim_time` (
  `time_id` INT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `month` VARCHAR(20) NULL DEFAULT NULL,
  `quarter` VARCHAR(10) NULL DEFAULT NULL,
  `year` INT NULL DEFAULT NULL,
  PRIMARY KEY (`time_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globalgadgets_dw`.`fact_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globalgadgets_dw`.`fact_sales` (
  `sales_id` INT NOT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `time_id` INT NULL DEFAULT NULL,
  `city_id` INT NULL DEFAULT NULL,
  `quantity_sold` INT NULL DEFAULT NULL,
  `total_sales` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`sales_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `time_id` (`time_id` ASC) VISIBLE,
  INDEX `city_id` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fact_sales_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `globalgadgets_dw`.`dim_product` (`product_id`),
  CONSTRAINT `fact_sales_ibfk_2`
    FOREIGN KEY (`customer_id`)
    REFERENCES `globalgadgets_dw`.`dim_customer` (`customer_id`),
  CONSTRAINT `fact_sales_ibfk_3`
    FOREIGN KEY (`time_id`)
    REFERENCES `globalgadgets_dw`.`dim_time` (`time_id`),
  CONSTRAINT `fact_sales_ibfk_4`
    FOREIGN KEY (`city_id`)
    REFERENCES `globalgadgets_dw`.`dim_city` (`city_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
